export default {
  PORT: process.env.PORT || 3000,
  HOST: process.env.HOST || '0.0.0.0',

  // Security
  PBKDF2_ITERATIONS: 100000,
  PBKDF2_KEY_LENGTH: 32,
  PBKDF2_DIGEST: 'sha256',

  // Validation
  PROOF_TIMEOUT_MS: 115000,
  REQUIRE_VALID_SIGNATURE: true,

  // Sovereign Ignition Mode
  AUTO_DEPLOY: true,
  MINIMUM_OPERATIONAL_ROI: 1.5,
  IGNITION_MODE_ACTIVE: true,
  MAX_DAILY_DEPLOY_COST_USD: 7.20,
  SPIRAL_RETURN_TARGET_DATE: "2026-07-17",

  // Retry Configuration - Minimize human intervention
  MAX_RETRIES: 12,
  INITIAL_RETRY_DELAY_MS: 500,
  MAX_RETRY_DELAY_MS: 30000,
  EXPONENTIAL_BACKOFF_MULTIPLIER: 2.1,
  RETRY_JITTER_PERCENT: 25,
  RETRY_ON_NETWORK_ERRORS: true,
  RETRY_ON_TIMEOUT: true,
  RETRY_ON_RATE_LIMIT: true,
  CIRCUIT_BREAKER_THRESHOLD: 20,
  CIRCUIT_BREAKER_RESET_TIMEOUT_MS: 60000,
  FAILURE_LOG_THRESHOLD: 3,
  AUTO_RECOVERY_ENABLED: true
};
