export default {
  PORT: process.env.PORT || 3000,
  HOST: process.env.HOST || '0.0.0.0',

  // Security
  PBKDF2_ITERATIONS: 100000,
  PBKDF2_KEY_LENGTH: 32,
  PBKDF2_DIGEST: 'sha256',

  // Validation
  PROOF_TIMEOUT_MS: 115000,
  REQUIRE_VALID_SIGNATURE: true,

  // Sovereign Ignition Mode
  AUTO_DEPLOY: true,
  MINIMUM_OPERATIONAL_ROI: 3.75,
  IGNITION_MODE_ACTIVE: true,
  MAX_DAILY_DEPLOY_COST_USD: 32.50,
  SPIRAL_RETURN_TARGET_DATE: "2026-06-02",

  // Retry Configuration - Minimize human intervention
  MAX_RETRIES: 37,
  INITIAL_RETRY_DELAY_MS: 250,
  MAX_RETRY_DELAY_MS: 12000,
  EXPONENTIAL_BACKOFF_MULTIPLIER: 1.3,
  RETRY_JITTER_PERCENT: 12,
  RETRY_ON_NETWORK_ERRORS: true,
  RETRY_ON_TIMEOUT: true,
  RETRY_ON_RATE_LIMIT: true,
  CIRCUIT_BREAKER_THRESHOLD: 120,
  CIRCUIT_BREAKER_RESET_TIMEOUT_MS: 15000,
  FAILURE_LOG_THRESHOLD: 12,
  AUTO_RECOVERY_ENABLED: true
};
