#!/usr/bin/env bash
set -euo pipefail
PAYLOAD="${1:?payload path required}"
EXPECTED_SHA256="${2:?expected sha256 required}"
EXPECTED_CONTENT_ADDRESS="${3:?expected content address required}"
test -f "$PAYLOAD"
ACTUAL_SHA256="$(sha256sum "$PAYLOAD" | awk "{print \$1}")"
test "$ACTUAL_SHA256" = "$EXPECTED_SHA256"
test "$EXPECTED_CONTENT_ADDRESS" = "sha256:${ACTUAL_SHA256}"
echo "DA_UPLOAD_SIMULATOR_RECEIVED=TRUE"
echo "PAYLOAD_PATH=${PAYLOAD}"
echo "PAYLOAD_HASH_MATCH=true"
echo "PAYLOAD_SHA256=${ACTUAL_SHA256}"
echo "CONTENT_ADDRESS_EXPECTED=${EXPECTED_CONTENT_ADDRESS}"
echo "PRIVATE_KEY_USED=false"
echo "TRANSACTION_SIGNED=false"
echo "TRANSACTION_BROADCAST=false"
echo "STORAGE_WRITE_ATTEMPTED=false"
echo "CHAIN_STATE_MUTATED=false"
