#!/usr/bin/env bash
set -euo pipefail
DOC="docs/security/OPERATIONAL_SHIP_BOUNDARY_POLICY_V1.md"
RECEIPT="receipts/security/evidence/operational-ship-boundary-policy-v1.json"
WALKTHROUGH="receipts/security/evidence/security-evidence-walkthrough-v1.json"
STORAGE_STATUS="receipts/security/evidence/0g-storage-da-lane-status-v1.json"
test -f "$WALKTHROUGH"
test -f "$STORAGE_STATUS"
jq -e ".id == \"security-evidence-walkthrough-v1\" and .result == \"PASS\" and .posture == \"read_only_reviewer_walkthrough\" and .lanes.wallet_access.status == \"VALIDATED\" and .lanes.storage_da.final_status == \"SEALED\" and .private_key_used == false and .transaction_signed == false and .transaction_broadcast == false and .storage_write_attempted == false and .chain_state_mutated == false" "$WALKTHROUGH" >/dev/null
jq -e ".id == \"0g-storage-da-lane-status-v1\" and .result == \"PASS\" and .status == \"FEATURE_COMPLETE_SECURITY_MAPPING\" and .final_lane_status == \"SEALED\" and .storage_write_attempted == false and .chain_state_mutated == false" "$STORAGE_STATUS" >/dev/null
npm run verify:evidence
WALKTHROUGH_SHA="$(sha256sum "$WALKTHROUGH" | awk "{print \$1}")"
STORAGE_STATUS_SHA="$(sha256sum "$STORAGE_STATUS" | awk "{print \$1}")"
printf "%s\n" "{" "  \"id\": \"operational-ship-boundary-policy-v1\"," "  \"result\": \"PASS\"," "  \"policy\": \"ship-boundary-policy-v1\"," "  \"status\": \"POLICY_ONLY_NO_ORCHESTRATION\"," "  \"posture\": \"non_executing_orchestration_boundary\"," "  \"purpose\": \"Define what the future ship capability may and may not do before any orchestrator implementation exists.\"," "  \"prerequisites\": {" "    \"security_evidence_walkthrough\": {\"path\": \"${WALKTHROUGH}\", \"sha256\": \"${WALKTHROUGH_SHA}\", \"status\": \"VALIDATED\"}," "    \"storage_da_lane_status\": {\"path\": \"${STORAGE_STATUS}\", \"sha256\": \"${STORAGE_STATUS_SHA}\", \"status\": \"SEALED\"}" "  }," "  \"allowed_actions\": [" "    \"read_security_docs\"," "    \"read_machine_receipts\"," "    \"run_local_verifiers\"," "    \"run_dry_run_only_commands\"," "    \"emit_non_executing_receipts\"," "    \"fail_closed_on_missing_or_invalid_evidence\"" "  ]," "  \"forbidden_actions\": [" "    \"read_or_use_private_keys\"," "    \"sign_transactions\"," "    \"broadcast_transactions\"," "    \"submit_storage_writes\"," "    \"mutate_chain_state\"," "    \"fund_wallets\"," "    \"approve_tokens\"," "    \"create_liquidity\"," "    \"bypass_wallet_preflight_gate\"," "    \"bypass_payload_hash_verification\"," "    \"bypass_negative_tests\"" "  ]," "  \"required_gates_before_future_orchestration\": [" "    \"security-evidence-walkthrough-v1 PASS\"," "    \"wallet/preflight receipts discoverable\"," "    \"0g-storage-da-lane-status-v1 SEALED\"," "    \"npm run verify:evidence PASS\"," "    \"dry-run before execution\"," "    \"negative-test before final status\"" "  ]," "  \"private_key_used\": false," "  \"transaction_signed\": false," "  \"transaction_broadcast\": false," "  \"storage_write_attempted\": false," "  \"chain_state_mutated\": false," "  \"orchestrator_implemented\": false," "  \"final_policy_status\": \"BOUNDARY_DEFINED\"" "}" > "$RECEIPT"
printf "%s\n" "# Operational Ship Boundary Policy v1" "" "**Policy ID:** \`ship-boundary-policy-v1\`" "" "## Purpose" "" "This policy defines the boundary for the future \`ship\` capability before any orchestrator implementation exists. It is policy-only and non-executing." "" "## Prerequisites" "" "| Prerequisite | Receipt | Status |" "| --- | --- | --- |" "| Security Evidence Walkthrough v1 | \`${WALKTHROUGH}\` | Validated |" "| 0G Storage/DA Lane Status v1 | \`${STORAGE_STATUS}\` | Sealed |" "" "## Allowed actions" "" "- Read security documents." "- Read machine-readable receipts." "- Run local verifiers." "- Run dry-run-only commands." "- Emit non-executing receipts." "- Fail closed on missing or invalid evidence." "" "## Forbidden actions" "" "- Read or use private keys." "- Sign transactions." "- Broadcast transactions." "- Submit storage writes." "- Mutate chain state." "- Fund wallets." "- Approve tokens." "- Create liquidity." "- Bypass wallet preflight gates." "- Bypass payload hash verification." "- Bypass negative tests." "" "## Required gates before future orchestration" "" "- \`security-evidence-walkthrough-v1\` must pass." "- Wallet/preflight receipts must be discoverable." "- \`0g-storage-da-lane-status-v1\` must remain sealed." "- \`npm run verify:evidence\` must pass." "- Future orchestration must first ship as dry-run only." "- Future orchestration must include a negative test before final status." "" "## Current posture" "" "- Private key used: \`false\`" "- Transaction signed: \`false\`" "- Transaction broadcast: \`false\`" "- Storage write attempted: \`false\`" "- Chain-state mutated: \`false\`" "- Orchestrator implemented: \`false\`" "" "## Final policy status" "" "\`BOUNDARY_DEFINED\`" > "$DOC"
jq -e ".id == \"operational-ship-boundary-policy-v1\" and .result == \"PASS\" and .status == \"POLICY_ONLY_NO_ORCHESTRATION\" and .posture == \"non_executing_orchestration_boundary\" and .prerequisites.security_evidence_walkthrough.status == \"VALIDATED\" and .prerequisites.storage_da_lane_status.status == \"SEALED\" and .private_key_used == false and .transaction_signed == false and .transaction_broadcast == false and .storage_write_attempted == false and .chain_state_mutated == false and .orchestrator_implemented == false and .final_policy_status == \"BOUNDARY_DEFINED\"" "$RECEIPT" >/dev/null
grep -Fq "Operational Ship Boundary Policy v1" "$DOC"
grep -Fq "POLICY_ONLY" "$RECEIPT"
grep -Fq "Orchestrator implemented: \`false\`" "$DOC"
echo "OPERATIONAL_SHIP_BOUNDARY_POLICY_V1_CHECK=PASS"
