#!/usr/bin/env python3
"""
Quantum Pi Forge - 0G Mainnet Mini-Audit Generator
Audit-to-Soul Funnel for SASK AI EXPO April 27

This script scans the 0G Aristotle Mainnet, generates sovereign health audits,
and creates ready-to-distribute Markdown reports for contract owners.
Implements the "Trojan Horse" client acquisition strategy.
"""
import os
import sys
import json
from web3 import Web3
from datetime import datetime

# Configuration
FORGE_ROOT = "/home/kris/forge"
IDENTITY_MAP = os.path.join(FORGE_ROOT, "forge_identity_map.txt.bak")
RPC_ENDPOINT = "https://rpc.0g.ai"
EXPO_DATE = datetime(2026, 4, 27)

def init_w3():
    """Initialize Web3 connection to 0G Mainnet"""
    w3 = Web3(Web3.HTTPProvider(RPC_ENDPOINT))
    if not w3.is_connected():
        print("❌ Failed to connect to 0G Mainnet RPC")
        sys.exit(1)
    return w3

def is_contract(w3, address):
    """Check if address is a smart contract (not EOA wallet)"""
    return len(w3.eth.get_code(address)) > 0

def calculate_validation_score(transaction_volume):
    """Validation Score algorithm: volume / 20"""
    return round(transaction_volume / 20, 2)

def is_local_sask_target(address):
    """Detect Saskatchewan Prairie ecosystem contracts"""
    # Identity map geotag lookup
    if os.path.exists(IDENTITY_MAP):
        with open(IDENTITY_MAP, 'r', errors='ignore') as f:
            for line in f:
                if address.lower() in line.lower():
                    if any(tag in line.lower() for tag in ['sask', 'saskatoon', 'regina', 'prairie', 'canada']):
                        return True
    return False

def generate_audit_report(w3, contract_address, block_number):
    """Generate complete mini-audit report for a contract"""
    
    address = Web3.to_checksum_address(contract_address)
    tx_count = w3.eth.get_transaction_count(address, block_number)
    balance = w3.eth.get_balance(address, block_number)
    balance_0g = w3.from_wei(balance, 'ether')
    
    validation_score = calculate_validation_score(tx_count)
    local_priority = is_local_sask_target(address)
    
    # Generate report content
    report = [
        f"# 🔍 Quantum Pi Forge - Sovereign Health Audit",
        f"## Contract: `{address}`",
        f"",
        f"### 📊 Audit Summary",
        f"| Metric | Value | Status |",
        f"|--------|-------|--------|",
        f"| Block Verified | {block_number:,} | ✅ |",
        f"| Transaction Volume | {tx_count:,} | ✅ |",
        f"| Current Balance | {round(balance_0g, 4)} 0G | ✅ |",
        f"| **Validation Score** | **{validation_score}** | ⚠️ |",
        f"| Soul Ledger Status | NOT REGISTERED | ❌ |",
        f"",
    ]
    
    if local_priority:
        report.extend([
            f"### 📍 LOCAL PRIORITY TARGET",
            f"> ✅ Contract located in SASK AI ecosystem",
            f"> Priority validation and onboarding available before April 27 Expo",
            f"",
        ])
    
    report.extend([
        f"### 🔒 Missing Soul Ledger Registration",
        f"This contract has not been anchored to the OINIO Soul System. This means:",
        f"- ❌ No sovereign identity verification for transactions",
        f"- ❌ No oracle resonance validation",
        f"- ❌ Not eligible for ethical yield distribution",
        f"- ❌ Missing permanent chain-of-trust audit trail",
        f"",
        f"### 🚀 Next Steps",
        f"1. Deploy Soul Ledger anchor transaction to block {block_number + 100000:,}",
        f"2. Register contract metadata with the Forge identity map",
        f"3. Enable automatic guardian consensus validation",
        f"",
        f"---",
        f"*Audit generated by Quantum Pi Forge Guardian Agent*",
        f"*For SASK AI EXPO 2026 | Prince Albert, Saskatchewan*",
        f"https://quantumpiforge.com",
    ])
    
    return '\n'.join(report), validation_score

def scan_mainnet(w3, block_range=1000):
    """Scan latest blocks for active contracts"""
    current_block = w3.eth.block_number
    print(f"🔍 Scanning 0G Mainnet from block {current_block - block_range:,} to {current_block:,}")
    print("")
    
    contracts_found = 0
    audits_generated = 0
    
    for block_num in range(current_block - block_range, current_block):
        block = w3.eth.get_block(block_num, full_transactions=True)
        
        for tx in block.transactions:
            if tx.to and is_contract(w3, tx.to):
                contracts_found += 1
                
                report, score = generate_audit_report(w3, tx.to, block_num)
                
                # Only generate reports for contracts with meaningful activity
                if score > 5.0:
                    filename = f"audit_{tx.to.lower()}_{current_block}.md"
                    output_path = os.path.join(FORGE_ROOT, "Quantum-pi-forge", "guardian", "audits", filename)
                    os.makedirs(os.path.dirname(output_path), exist_ok=True)
                    
                    with open(output_path, 'w') as f:
                        f.write(report)
                    
                    audits_generated += 1
                    print(f"✅ Generated audit for {tx.to} | Score: {score}")
    
    print("")
    print(f"📋 Scan Complete:")
    print(f"   Blocks scanned: {block_range}")
    print(f"   Contracts found: {contracts_found}")
    print(f"   Audits generated: {audits_generated}")

if __name__ == "__main__":
    print("🔥 Quantum Pi Forge - Mini-Audit Generator")
    print(f"   SASK AI EXPO Readiness: {(EXPO_DATE - datetime.now()).days} days remaining")
    print("")
    
    w3 = init_w3()
    print("✅ Connected to 0G Aristotle Mainnet")
    print("")
    
    scan_mainnet(w3)